### PR TITLE
Add support for macos arm64

### PR DESCRIPTION
**Pull request by Androz2091**
**Please describe the changes this PR makes and why it should be merged:**

Implements @empressdaybreak suggestion in #76 into a mergeable pull request. I can confirm that it works perfectly on my arm64 mac.

**Semantic versioning classification:**

- [ ] This PR changes the library's interface (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by iCrawl** [comment]
Does this not need the arm64 config.h from the other PR?

**Comment by Androz2091** [comment]
It builds and works perfectly when trying to install from my fork. So I **guess** no.

**Comment by iCrawl** [comment]
Cool, thanks 👍

**Review by iCrawl — APPROVED** [review]

**Comment by ppichinenko** [comment]
Cool, it finally worked on m1, good job!

**Pull request merged**
